spring:
  application:
    name: openai-demo
  ai:
      openai:
        api-key: ${OPENAI_API_KEY:}
      vectorstore:
          chroma:
              initialize-schema: true
              collection-name: demo
#      chat:
#        options:
#          model: gpt-4o
#          max-tokens: 20